import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-batch-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const printers = await import('../src/core/printers.js');
const library = await import('../src/core/library.js');
const jobs = await import('../src/core/jobs.js');

const GCODE = ['; generated by PrusaSlicer 2.8.0', 'M83', 'G1 X0 Y0 E5', 'G1 X10 E50', '; estimated printing time (normal mode) = 10m 0s', '; filament_type = PLA'].join('\n');

let printerA;
let printerB;
let file;

const bothReady = () => waitFor(() => printers.isReady(printerA.id) && printers.isReady(printerB.id));

before(async () => {
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  printerA = printers.addPrinter({ name: 'Farm A', driver: 'virtual', connection: { simulationSpeed: 1 } });
  printerB = printers.addPrinter({ name: 'Farm B', driver: 'virtual', connection: { simulationSpeed: 1 } });
  file = library.addFromContent({ name: 'farm.gcode', content: GCODE });
  jobs.startQueue();
  await bothReady();
});

after(async () => {
  jobs.stopQueue();
  jobs.flushJobs();
  await printers.stopAll();
});

test('a batch runs on every selected printer at once, one copy each, and cancels as a whole', async () => {
  const result = await jobs.createBatch({ fileId: file.id, printerIds: [printerA.id, printerB.id] });
  assert.equal(result.started, 2);
  assert.deepEqual(result.skipped, []);
  assert.deepEqual(new Set(result.jobs.map((job) => job.printerId)), new Set([printerA.id, printerB.id]));
  assert.ok(result.jobs.every((job) => job.batch.id === result.batch && job.batch.total === 2 && job.status !== 'queued'));
  assert.equal(jobs.listJobs({ status: 'queued' }).length, 0);

  const canceled = await jobs.cancelBatch(result.batch, { force: true });
  assert.equal(canceled.canceled, 2);
  assert.ok(result.jobs.every((job) => jobs.getJob(job.id).status === 'canceled'));
});

test('printers without a confirmed clear bed are skipped, not queued', async () => {
  await bothReady();
  printers.setBedClear(printerA.id, false);
  printers.setBedClear(printerB.id, true);
  const result = await jobs.createBatch({ fileId: file.id, printerIds: [printerA.id, printerB.id] });
  assert.equal(result.started, 1);
  assert.equal(result.jobs[0].printerId, printerB.id);
  assert.equal(result.jobs[0].batch.total, 1);
  assert.deepEqual(
    result.skipped.map((item) => [item.printerId, item.reason]),
    [[printerA.id, 'error.bed_not_clear']],
  );
  assert.equal(jobs.listJobs({ status: 'queued' }).length, 0);
  await jobs.cancelBatch(result.batch, { force: true });
});

test('no printer ready means an error and no job created', async () => {
  await bothReady();
  printers.setBedClear(printerA.id, false);
  printers.setBedClear(printerB.id, false);
  const before = jobs.listJobs({ limit: 500 }).length;
  await assert.rejects(jobs.createBatch({ fileId: file.id }), { key: 'error.batch_none_ready' });
  assert.equal(jobs.listJobs({ limit: 500 }).length, before);
  await assert.rejects(jobs.cancelBatch('bat_missing'), { key: 'error.batch_not_found' });
});
