import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-insights-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const printers = await import('../src/core/printers.js');
const library = await import('../src/core/library.js');
const jobs = await import('../src/core/jobs.js');
const insights = await import('../src/core/insights.js');
const filament = await import('../src/core/filament.js');

const GCODE = [
  '; generated by PrusaSlicer 2.8.0',
  'M83',
  'G1 X0 Y0 E300',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';TYPE:Skirt/Brim',
  'G1 X1 E200',
  ';TYPE:External perimeter',
  'G1 X2 E3000',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';TYPE:Support material',
  'G1 X3 E500',
  ';TYPE:Perimeter',
  'G1 X4 E3000',
  '; estimated printing time (normal mode) = 10m 0s',
  '; layer_height = 0.2',
  '; filament_type = PLA',
].join('\n');

let printerA;
let printerB;
let file;

before(async () => {
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  printerA = printers.addPrinter({ name: 'Máy A', driver: 'virtual', connection: { simulationSpeed: 1000 }, powerW: 200, hourlyCost: 1000 });
  printerB = printers.addPrinter({ name: 'Máy B', driver: 'virtual', connection: { simulationSpeed: 1000 } });
  file = library.addFromContent({ name: 'moc-khoa.gcode', content: GCODE });
  insights.startInsights();
  jobs.startQueue();
  await waitFor(() => printers.isReady(printerA.id) && printers.isReady(printerB.id));
});

after(async () => {
  insights.stopInsights();
  jobs.stopQueue();
  jobs.flushJobs();
  await printers.stopAll();
});

test('Chống trùng: thêm lại đúng nội dung thì trả file cũ, không tạo bản mới', () => {
  const again = library.addFromContent({ name: 'ten-khac.gcode', content: GCODE });
  assert.equal(again.duplicate, true);
  assert.equal(again.id, file.id);
  assert.equal(library.getFile(file.id).sha256.length, 64);
});

test('Cuộn nhựa: gắn vào khay đang có cuộn khác thì cuộn cũ được tháo ra', () => {
  const first = filament.saveSpool({ name: 'PLA đen', material: 'pla', printerId: printerA.id, slot: 0, remainingG: 50 });
  assert.equal(first.material, 'PLA');
  assert.equal(first.density, 1.24);
  assert.equal(first.low, true);
  const second = filament.saveSpool({ name: 'PLA trắng', material: 'PLA', printerId: printerA.id, slot: 0, remainingG: 800, pricePerKg: 400000 });
  assert.equal(filament.getSpool(first.id).printerId, null);
  assert.equal(filament.listSpools({ printerId: printerA.id }).length, 1);
  assert.equal(filament.adjustSpool(second.id, { deltaG: -100 }).remainingG, 700);
  filament.deleteSpool(first.id);
  assert.throws(() => filament.getSpool(first.id), { key: 'error.spool_not_found' });
});

test('Kiểm tra trước khi in: đủ nhựa, đúng loại, có chi phí và giờ xong', () => {
  const check = filament.preflight({ fileId: file.id, printerId: printerA.id });
  assert.ok(check.material.totalG > 20);
  assert.ok(check.material.wasteG > 0);
  assert.equal(check.spools[0].enough, true);
  assert.equal(check.spools[0].materialMatch, true);
  assert.deepEqual(check.warnings, []);
  assert.ok(check.cost.filament > 0);
  assert.equal(check.cost.powerW, 200);
  assert.equal(check.estimate.estimatedTime, 600);
  assert.ok(check.estimate.finishAt);

  const spool = filament.listSpools({ printerId: printerA.id })[0];
  filament.adjustSpool(spool.id, { remainingG: 5 });
  assert.equal(filament.preflight({ fileId: file.id, printerId: printerA.id }).warnings[0].code, 'spool_low');
  filament.adjustSpool(spool.id, { remainingG: 700 });
});

test('In xong thì ghi sổ, trừ nhựa vào cuộn, tách phần thải và cộng giờ bảo trì', async () => {
  const spool = filament.listSpools({ printerId: printerA.id })[0];
  const job = await jobs.createJob({ printerId: printerA.id, fileId: file.id });
  const done = await waitFor(() => {
    const current = jobs.getJob(job.id);
    return current.status === 'completed' && current.material ? current : null;
  });
  assert.ok(done.material.usedG > 20);
  assert.ok(Math.abs(done.material.wasteG - (done.material.grams.support + done.material.grams.adhesion + done.material.grams.purge)) < 0.05);
  assert.ok(done.cost.total > 0);
  const left = filament.getSpool(spool.id).remainingG;
  assert.ok(Math.abs(left - (700 - done.material.usedG)) < 0.2, `còn ${left}`);

  const stats = insights.printStats({ days: 7 });
  assert.equal(stats.totals.completed, 1);
  assert.equal(stats.totals.successRate, 100);
  assert.equal(stats.printers[0].key, printerA.id);
  assert.equal(stats.materials[0].key, 'PLA');
  assert.ok(stats.totals.waste.support > 0);
  assert.ok(insights.statsDigest({ printerId: printerA.id }).length > 0);

  const maintenance = insights.listMaintenance(printerA.id);
  assert.equal(maintenance.tasks.length, 4);
  assert.equal(maintenance.usage.jobs, 1);
  const custom = insights.addMaintenance(printerA.id, { name: 'Thay dây curoa', intervalHours: 1000 });
  assert.equal(custom.custom, true);
  assert.equal(insights.completeMaintenance(printerA.id, custom.id).usedHours, 0);
  insights.deleteMaintenance(printerA.id, custom.id);
  assert.throws(() => insights.completeMaintenance(printerA.id, custom.id), { key: 'error.maintenance_not_found' });
});

test('Hàng đợi chung: ưu tiên cao chạy trước, đổi thứ tự được và máy rảnh tự nhận job', async () => {
  const model = library.addFromContent({ name: 'chua-cat.stl', content: 'solid x' });
  await assert.rejects(jobs.createJob({ printerId: 'any', fileId: model.id }), { key: 'error.no_matching_printer' });

  const low = await jobs.createJob({ printerId: 'any', fileId: file.id });
  const high = await jobs.createJob({ printerId: 'any', fileId: file.id, priority: 5 });
  assert.equal(low.status, 'queued');
  assert.equal(low.printerId, null);
  assert.equal(jobs.stats().queuedAny, 2);

  const order = () =>
    jobs
      .listJobs({ status: 'queued' })
      .sort((a, b) => b.priority - a.priority || a.position - b.position)
      .map((item) => item.id);
  assert.equal(order()[0], high.id);
  jobs.moveJob(low.id, 'top');
  assert.equal(jobs.getJob(low.id).priority, 5);
  assert.equal(order()[0], low.id);

  printers.setBedClear(printerA.id, true);
  printers.setBedClear(printerB.id, false);
  await printers.updatePrinter(printerA.id, { autoStartQueue: true });
  jobs.processQueue();
  const started = await waitFor(() => (jobs.getJob(low.id).printerId ? jobs.getJob(low.id) : null));
  assert.equal(started.printerId, printerA.id);
  assert.equal(jobs.getJob(high.id).status, 'queued');

  await waitFor(() => jobs.getJob(low.id).status === 'completed');
  await printers.updatePrinter(printerA.id, { autoStartQueue: false });
  printers.setBedClear(printerB.id, true);
  const moved = jobs.startJob(high.id, { printerId: printerB.id });
  assert.equal(moved.printerId, printerB.id);
  await waitFor(() => jobs.getJob(high.id).status === 'completed');
  library.deleteFile(model.id);
});
