import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-jobs-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const printers = await import('../src/core/printers.js');
const library = await import('../src/core/library.js');
const jobs = await import('../src/core/jobs.js');

const GCODE = ['; generated by PrusaSlicer 2.8.0', 'M140 S60', 'M104 S210', ';Z:0.2', ';Z:2', '; estimated printing time (normal mode) = 10m 0s', '; layer_height = 0.2'].join('\n');

let printer;
let file;

before(async () => {
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  printer = printers.addPrinter({ name: 'Sim', driver: 'virtual', connection: { simulationSpeed: 1000 } });
  file = library.addFromContent({ name: 'Bản in thử.gcode', content: GCODE });
  jobs.startQueue();
  await waitFor(() => printers.isReady(printer.id));
});

after(async () => {
  jobs.stopQueue();
  jobs.flushJobs();
  await printers.stopAll();
});

test('Library reads metadata when a file is added', async () => {
  assert.equal(file.format, 'gcode');
  assert.equal(file.meta.estimatedTime, 600);
  assert.equal(file.meta.layerCount, 10);
  assert.throws(() => library.addFromContent({ name: 'ghi_chu.txt', content: 'x' }), { key: 'error.file_type_unsupported' });

  const model = library.addFromContent({ name: 'model.stl', content: 'solid' });
  assert.equal(model.format, 'model');
  await assert.rejects(jobs.createJob({ printerId: printer.id, fileId: model.id }), { key: 'error.file_format_unsupported' });
  library.deleteFile(model.id);
});

test('Print now: upload, start and track through to completion', async () => {
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'now' });
  assert.equal(job.remoteName, null);
  const done = await waitFor(() => {
    const current = jobs.getJob(job.id);
    return ['completed', 'failed', 'canceled'].includes(current.status) ? current : null;
  });
  assert.equal(done.status, 'completed', done.error ?? '');
  assert.equal(done.remoteName, 'Ban_in_thu.gcode');
  assert.equal(done.progress, 100);
  assert.equal(done.layer, 10);
  assert.equal(library.getFile(file.id).printCount, 1);
  assert.equal(printers.getPrinter(printer.id).bedClear, false);
});

test('An uncleared bed blocks printing now unless confirmed', async () => {
  await assert.rejects(jobs.createJob({ printerId: printer.id, fileId: file.id }), { key: 'error.bed_not_clear' });
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, confirmBedClear: true });
  await waitFor(() => jobs.getJob(job.id).status === 'printing');
  await assert.rejects(jobs.createJob({ printerId: printer.id, fileId: file.id, confirmBedClear: true }), { key: 'error.printer_has_active_job' });
  await assert.rejects(printers.command(printer.id, 'jog', { x: 10 }), { key: 'error.printer_busy_printing' });

  await printers.command(printer.id, 'cancel');
  const canceled = await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? jobs.getJob(job.id) : null));
  assert.ok(canceled.error);
});

test('The queue only runs itself with autoStartQueue on and the bed clear', async () => {
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'queue' });
  assert.equal(job.status, 'queued');
  await new Promise((resolve) => setTimeout(resolve, 1500));
  assert.equal(jobs.getJob(job.id).status, 'queued');

  await printers.updatePrinter(printer.id, { autoStartQueue: true });
  await new Promise((resolve) => setTimeout(resolve, 1500));
  assert.equal(jobs.getJob(job.id).status, 'queued');

  printers.setBedClear(printer.id, true);
  const done = await waitFor(() => (jobs.getJob(job.id).status === 'completed' ? jobs.getJob(job.id) : null));
  assert.equal(done.origin, 'api');
  assert.throws(() => library.deleteFile('fil_missing'), { key: 'error.file_not_found' });
});

test('Safety limits on control commands', async () => {
  await assert.rejects(printers.command(printer.id, 'temperature', { heater: 'nozzle', target: 400 }), { key: 'error.temperature_limit' });
  await assert.rejects(printers.command(printer.id, 'gcode', { gcode: 'M104 S999' }), { key: 'error.temperature_limit' });
  await assert.rejects(printers.command(printer.id, 'gcode', { gcode: 'M502' }), { key: 'error.gcode_blocked' });
  await assert.rejects(printers.command(printer.id, 'jog', { x: 5000 }), { key: 'error.field_invalid' });
  await assert.rejects(printers.command(printer.id, 'fly'), { key: 'error.command_unknown' });
  const result = await printers.command(printer.id, 'gcode', { gcode: 'M105' });
  assert.match(result.responses[0], /^ok T:/);
});

test('A printer with an open job cannot be removed, removing it cancels the queued job', async () => {
  await printers.updatePrinter(printer.id, { autoStartQueue: false });
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'queue' });
  assert.throws(() => library.deleteFile(file.id), { key: 'error.file_in_use' });
  await printers.removePrinter(printer.id);
  await waitFor(() => jobs.getJob(job.id).status === 'canceled');
});

test('Calibration: requires a clear bed, accepts only supported items, creates no job', async () => {
  // The previous test removed the shared printer, so build a dedicated one for the two calibration tests.
  printer = printers.addPrinter({ name: 'Sim bed level', driver: 'virtual', connection: { simulationSpeed: 1000 } });
  await waitFor(() => printers.isReady(printer.id));
  printers.setBedClear(printer.id, false);
  await assert.rejects(printers.command(printer.id, 'calibrate', { options: ['bedLeveling'] }), { key: 'error.bed_not_clear' });

  printers.setBedClear(printer.id, true);
  await assert.rejects(printers.command(printer.id, 'calibrate', { options: [] }), { key: 'error.calibration_no_option' });
  await assert.rejects(printers.command(printer.id, 'calibrate', { options: ['xyz'] }), { key: 'error.field_invalid' });
  await assert.rejects(printers.command(printer.id, 'calibrate', { options: ['nozzleOffset'] }), { key: 'error.calibration_unsupported' });

  const before = jobs.stats().total;
  const result = await printers.command(printer.id, 'calibrate', { options: ['bedLeveling', 'motorNoise'] });
  assert.deepEqual(result.options, ['bedLeveling', 'motorNoise']);

  const running = await waitFor(() => printers.statusOf(printer.id).extra?.calibration ?? null);
  assert.equal(running.steps, 2);
  assert.ok(running.remaining > 0);
  assert.equal(printers.getPrinter(printer.id).status.job, null);
  assert.equal(jobs.stats().total, before, 'calibration must not create any job');

  await printers.command(printer.id, 'cancel');
  await waitFor(() => (printers.statusOf(printer.id).extra?.calibration === null ? true : null));
});

test('Calibration: the virtual printer reports the items it supports', () => {
  const detail = printers.getPrinter(printer.id);
  assert.equal(detail.capabilities.calibrate, true);
  assert.deepEqual(detail.calibrations, ['bedLeveling', 'vibration', 'motorNoise']);
});

test('Camera: a password inside the URL is not exposed, and editing the printer keeps it', async () => {
  const cam = printers.addPrinter({
    name: 'Klipper ext cam',
    driver: 'moonraker',
    connection: { host: '127.0.0.1', port: 7125, cameraUrl: 'http://cam:matkhau@192.168.9.9/snapshot.jpg' },
  });

  const shown = printers.getPrinter(cam.id).connection.cameraUrl;
  assert.equal(shown, 'http://cam:***@192.168.9.9/snapshot.jpg');
  assert.equal(printers.getRecord(cam.id).connection.cameraUrl, 'http://cam:matkhau@192.168.9.9/snapshot.jpg');

  await printers.updatePrinter(cam.id, { name: 'Klipper ext cam 2', connection: { host: '127.0.0.1', port: 7125, cameraUrl: shown } });
  assert.equal(printers.getRecord(cam.id).connection.cameraUrl, 'http://cam:matkhau@192.168.9.9/snapshot.jpg');

  await printers.updatePrinter(cam.id, {
    connection: { host: '127.0.0.1', port: 7125, cameraUrl: 'http://cam:khacroi@192.168.9.9/snapshot.jpg' },
  });
  assert.equal(printers.getRecord(cam.id).connection.cameraUrl, 'http://cam:khacroi@192.168.9.9/snapshot.jpg');

  await printers.removePrinter(cam.id);
});
