import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { extractMetadata, fileFormat, packMesh, parseDuration, readPlateMesh } from '../src/gcode/metadata.js';
import { remoteFileName } from '../src/drivers/base.js';
import { makeZip, makeZip64 } from './helpers.js';

const dir = mkdtempSync(path.join(tmpdir(), 'p3d-meta-'));
const PNG = Buffer.from('89504e470d0a1a0a0000000d4948445200000001000000010806000000', 'hex');

function write(name, content) {
  const file = path.join(dir, name);
  writeFileSync(file, content);
  return file;
}

test('parseDuration understands slicer time formats', () => {
  assert.equal(parseDuration('1h 2m 3s'), 3723);
  assert.equal(parseDuration('12m 30s'), 750);
  assert.equal(parseDuration('1d 2h 0m 0s'), 93600);
  assert.equal(parseDuration('3600'), 3600);
  assert.equal(parseDuration(undefined), null);
});

test('fileFormat recognizes the extension', () => {
  assert.equal(fileFormat('part.GCODE'), 'gcode');
  assert.equal(fileFormat('part.bgcode'), 'bgcode');
  assert.equal(fileFormat('plate.gcode.3mf'), '3mf');
  assert.equal(fileFormat('model.stl'), 'model');
  assert.equal(fileFormat('model.obj'), 'model');
  assert.equal(fileFormat('note.txt'), null);
});

test('PrusaSlicer G-code: time, filament, temperatures, layer count and thumbnail', () => {
  const thumb = PNG.toString('base64');
  const file = write(
    'prusa.gcode',
    [
      '; generated by PrusaSlicer 2.8.0+win64 on 2026-01-01',
      `; thumbnail begin 16x16 ${thumb.length}`,
      `; ${thumb}`,
      '; thumbnail end',
      'M140 S65',
      'M104 S220',
      ';LAYER_CHANGE',
      ';Z:0.2',
      'G1 X1 Y1 E1',
      ';LAYER_CHANGE',
      ';Z:10',
      'G1 X2 Y2 E2',
      '; filament used [mm] = 1500.5',
      '; filament used [g] = 4.47',
      '; estimated printing time (normal mode) = 1h 5m 0s',
      '; filament_type = PETG;PLA',
      '; layer_height = 0.2',
      '; nozzle_diameter = 0.4,0.4',
      '; printer_model = MK4S',
    ].join('\n'),
  );
  const { meta, thumbnail } = extractMetadata(file, 'prusa.gcode');
  assert.equal(meta.slicer, 'PrusaSlicer 2.8.0+win64');
  assert.equal(meta.estimatedTime, 3900);
  assert.equal(meta.filamentLengthMm, 1500.5);
  assert.equal(meta.filamentWeightG, 4.47);
  assert.equal(meta.filamentType, 'PETG');
  assert.equal(meta.nozzleDiameter, 0.4);
  assert.equal(meta.printerModel, 'MK4S');
  assert.equal(meta.nozzleTemp, 220);
  assert.equal(meta.bedTemp, 65);
  assert.equal(meta.maxZ, 10);
  assert.equal(meta.layerCount, 50);
  assert.equal(thumbnail.mime, 'image/png');
  assert.deepEqual(thumbnail.buffer, PNG);
});

test('Cura G-code: ;TIME, ;LAYER_COUNT and filament metres', () => {
  const file = write(
    'cura.gcode',
    [';FLAVOR:Marlin', ';TIME:5025', ';Filament used: 2.5m', ';Layer height: 0.12', ';Generated with Cura_SteamEngine 5.7.1', ';LAYER_COUNT:120', 'M104 S205'].join('\n'),
  );
  const { meta } = extractMetadata(file, 'cura.gcode');
  assert.equal(meta.slicer, 'Cura 5.7.1');
  assert.equal(meta.estimatedTime, 5025);
  assert.equal(meta.filamentLengthMm, 2500);
  assert.equal(meta.layerCount, 120);
  assert.equal(meta.layerHeight, 0.12);
  assert.equal(meta.nozzleTemp, 205);
});

test('G-code with only "total filament used [g]" still gives the filament weight', () => {
  const file = write('total.gcode', ['; generated by PrusaSlicer 2.8.1+MacOS-arm64', '; total filament used [g] = 23.45'].join('\n'));
  assert.equal(extractMetadata(file, 'total.gcode').meta.filamentWeightG, 23.45);
});

test('Binary G-code: reads the metadata block and thumbnail', () => {
  const header = Buffer.alloc(10);
  header.write('GCDE', 0, 'ascii');
  header.writeUInt32LE(1, 4);
  header.writeUInt16LE(0, 8);
  const block = (type, params, data) => {
    const head = Buffer.alloc(8);
    head.writeUInt16LE(type, 0);
    head.writeUInt16LE(0, 2);
    head.writeUInt32LE(data.length, 4);
    return Buffer.concat([head, params, data]);
  };
  const ini = Buffer.from('printer_model=MK4\nestimated printing time (normal mode)=10m 0s\nfilament_type=PLA\n');
  const thumbParams = Buffer.alloc(6);
  thumbParams.writeUInt16LE(0, 0);
  thumbParams.writeUInt16LE(16, 2);
  thumbParams.writeUInt16LE(16, 4);
  const file = write(
    'part.bgcode',
    Buffer.concat([header, block(0, Buffer.alloc(2), ini), block(5, thumbParams, PNG), block(1, Buffer.alloc(2), Buffer.from('G28'))]),
  );
  const { meta, thumbnail } = extractMetadata(file, 'part.bgcode');
  assert.equal(meta.printerModel, 'MK4');
  assert.equal(meta.estimatedTime, 600);
  assert.equal(meta.filamentType, 'PLA');
  assert.deepEqual(thumbnail.buffer, PNG);
});

test('Sliced 3MF: plate list, AMS filament and thumbnail', () => {
  const sliceInfo = `<?xml version="1.0"?><config>
    <plate><metadata key="index" value="1"/><metadata key="prediction" value="3600"/><metadata key="weight" value="12.5"/>
      <metadata key="nozzle_diameters" value="0.4"/><filament id="1" type="PLA" color="#FFFFFF" used_g="10"/><filament id="3" type="PETG" color="#000000" used_g="2.5"/></plate>
    <plate><metadata key="index" value="2"/><metadata key="prediction" value="120"/></plate>
  </config>`;
  const file = write(
    'plate.gcode.3mf',
    makeZip({
      '3D/3dmodel.model': '<model><metadata name="Application">BambuStudio-02.01.00</metadata></model>',
      'Metadata/slice_info.config': sliceInfo,
      'Metadata/plate_1.gcode': 'G28',
      'Metadata/plate_2.gcode': 'G28',
      'Metadata/plate_1.png': PNG,
    }),
  );
  const { meta, thumbnail } = extractMetadata(file, 'plate.gcode.3mf');
  assert.equal(meta.sliced, true);
  assert.equal(meta.slicer, 'BambuStudio 02.01.00');
  assert.equal(meta.plates.length, 2);
  assert.equal(meta.plates[0].estimatedTime, 3600);
  assert.deepEqual(meta.plates[0].filaments.map((item) => item.id), [1, 3]);
  assert.equal(meta.plates[1].gcode, 'Metadata/plate_2.gcode');
  assert.equal(meta.estimatedTime, 3600);
  assert.equal(meta.filamentType, 'PLA');
  assert.deepEqual(thumbnail.buffer, PNG);
});

test('An unsliced 3MF is marked sliced=false', () => {
  const file = write('model.3mf', makeZip({ '3D/3dmodel.model': '<model></model>' }));
  const { meta } = extractMetadata(file, 'model.3mf');
  assert.equal(meta.sliced, false);
  assert.deepEqual(meta.plates, []);
});

test('Unsliced 3MF: size, volume and overhang measured through the build item transform', () => {
  // A 10x20x30 box sits in its own object file; the build item rotates it 90 degrees about Z and moves it to the bed center.
  const corners = [[0, 0, 0], [10, 0, 0], [10, 20, 0], [0, 20, 0], [0, 0, 30], [10, 0, 30], [10, 20, 30], [0, 20, 30]];
  const faces = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [3, 7, 6], [3, 6, 2], [0, 4, 7], [0, 7, 3], [1, 2, 6], [1, 6, 5]];
  const objectModel = `<model><resources><object id="1" type="model"><mesh>
    <vertices>${corners.map(([x, y, z]) => `<vertex x="${x}" y="${y}" z="${z}"/>`).join('')}</vertices>
    <triangles>${faces.map(([a, b, c]) => `<triangle v1="${a}" v2="${b}" v3="${c}"/>`).join('')}</triangles>
  </mesh></object></resources></model>`;
  const rootModel = `<model><resources>
    <object id="2" type="model"><components><component p:path="/3D/Objects/object_1.model" objectid="1"/></components></object>
  </resources><build>
    <item objectid="2" transform="0 1 0 -1 0 0 0 0 1 128 128 0"/>
  </build></model>`;

  const file = write('cube.3mf', makeZip({ '3D/3dmodel.model': rootModel, '3D/Objects/object_1.model': objectModel }));
  const { meta } = extractMetadata(file, 'cube.3mf');
  assert.equal(meta.sliced, false);
  assert.equal(meta.triangles, 12);
  // The 90 degree Z rotation swaps the X and Y edges, the height stays.
  assert.deepEqual(meta.size, { x: 20, y: 10, z: 30 });
  assert.equal(meta.volumeCm3, 6);
  assert.equal(meta.overhangRatio, 0);
});

const MESH_CORNERS = [[0, 0, 0], [10, 0, 0], [10, 10, 0], [0, 10, 0], [0, 0, 10], [10, 0, 10], [10, 10, 10], [0, 10, 10]];
const MESH_FACES = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [3, 7, 6], [3, 6, 2], [0, 4, 7], [0, 7, 3], [1, 2, 6], [1, 6, 5]];

function cubeObject(id) {
  return `<object id="${id}" type="model"><mesh>
    <vertices>${MESH_CORNERS.map(([x, y, z]) => `<vertex x="${x}" y="${y}" z="${z}"/>`).join('')}</vertices>
    <triangles>${MESH_FACES.map(([a, b, c]) => `<triangle v1="${a}" v2="${b}" v3="${c}"/>`).join('')}</triangles>
  </mesh></object>`;
}

function platedFile(name) {
  const model = `<model><resources>${cubeObject(1)}${cubeObject(2)}</resources><build>
    <item objectid="1" transform="1 0 0 0 1 0 0 0 1 20 30 0"/>
    <item objectid="2" transform="1 0 0 0 1 0 0 0 1 60 60 0"/>
  </build></model>`;
  const settings = `<config>
    <object id="1"><metadata key="name" value="Block A"/></object>
    <object id="2"><metadata key="name" value="Block B"/></object>
    <plate><metadata key="plater_id" value="1"/><model_instance><metadata key="object_id" value="1"/></model_instance></plate>
    <plate><metadata key="plater_id" value="2"/><model_instance><metadata key="object_id" value="2"/></model_instance></plate>
  </config>`;
  return write(
    name,
    makeZip({
      '3D/3dmodel.model': model,
      'Metadata/model_settings.config': settings,
      'Metadata/project_settings.config': JSON.stringify({
        printable_area: ['0x0', '180x0', '180x180', '0x180'],
        printable_height: '180',
        printer_model: 'Bambu Lab A1 mini',
      }),
      'Metadata/plate_1.json': JSON.stringify({ bbox_all: [20, 30, 30, 40], bbox_objects: [] }),
      'Metadata/plate_2.json': JSON.stringify({ bbox_all: [60, 60, 70, 70], bbox_objects: [] }),
    }),
  );
}

test('A zip64-written 3MF still yields geometry instead of reading as empty', () => {
  const model = `<model><resources>${cubeObject(1)}</resources><build><item objectid="1"/></build></model>`;
  const file = write('zip64.3mf', makeZip64({ '[Content_Types].xml': '<Types/>', '3D/3dmodel.model': model }));

  const mesh = readPlateMesh(file, 'zip64.3mf', 1);
  assert.equal(mesh.objects.length, 1);
  assert.equal(mesh.objects[0].triangles, 12);
  assert.deepEqual(mesh.objects[0].bbox, [0, 0, 0, 10, 10, 10]);

  const { meta } = extractMetadata(file, 'zip64.3mf');
  assert.equal(meta.triangles, 12);
  assert.deepEqual(meta.size, { x: 10, y: 10, z: 10 });
});

test('Plate mesh: coordinates already transformed, names from model_settings, each plate returns only its own objects', () => {
  const file = platedFile('plated.3mf');

  const first = readPlateMesh(file, 'plated.3mf', 1);
  assert.equal(first.plate, 1);
  assert.deepEqual(first.plates, [1, 2]);
  assert.equal(first.bed.model, 'Bambu Lab A1 mini');
  assert.deepEqual([first.bed.maxX, first.bed.maxY, first.bed.maxZ], [180, 180, 180]);
  assert.equal(first.objects.length, 1);
  assert.equal(first.objects[0].name, 'Block A');
  assert.deepEqual(first.objects[0].bbox, [20, 30, 0, 30, 40, 10]);
  // Duplicate vertices are merged, so the 12-face box keeps only 8 vertices.
  assert.equal(first.objects[0].vertices.length / 3, 8);
  assert.equal(first.objects[0].triangles, 12);

  const second = readPlateMesh(file, 'plated.3mf', 2);
  assert.equal(second.objects.length, 1);
  assert.equal(second.objects[0].name, 'Block B');
  assert.deepEqual(second.objects[0].bbox, [60, 60, 0, 70, 70, 10]);
});

test('packMesh packs correctly: the JSON header, then vertices and indices per object', () => {
  const mesh = readPlateMesh(platedFile('packed.3mf'), 'packed.3mf', 1);
  const buffer = packMesh(mesh);

  const length = buffer.readUInt32LE(0);
  const header = JSON.parse(buffer.subarray(4, 4 + length).toString('utf8'));
  assert.equal(header.objects.length, 1);
  assert.equal(header.objects[0].vertexCount, 8);
  assert.equal(header.objects[0].indexCount, 36);

  const at = 4 + Math.ceil(length / 4) * 4;
  const vertices = new Float32Array(buffer.buffer, buffer.byteOffset + at, 24);
  const indices = new Uint32Array(buffer.buffer, buffer.byteOffset + at + 96, 36);
  assert.deepEqual([...vertices.slice(0, 3)], [20, 30, 0]);
  assert.equal(Math.max(...indices), 7);
  assert.equal(buffer.length, at + 96 + 144);
});

test('STL mesh: a single object and no bed data', () => {
  const triangles = MESH_FACES.map((face) => face.map((corner) => MESH_CORNERS[corner]));
  const stl = Buffer.alloc(84 + triangles.length * 50);
  stl.writeUInt32LE(triangles.length, 80);
  triangles.forEach((triangle, index) => {
    const offset = 84 + index * 50 + 12;
    triangle.flat().forEach((value, item) => stl.writeFloatLE(value, offset + item * 4));
  });

  const mesh = readPlateMesh(write('solo.stl', stl), 'solo.stl', 1);
  assert.equal(mesh.bed, null);
  assert.equal(mesh.objects.length, 1);
  assert.equal(mesh.objects[0].name, 'solo.stl');
  assert.deepEqual(mesh.objects[0].bbox, [0, 0, 0, 10, 10, 10]);
});

test('A corrupt file does not crash, it returns parseError', () => {
  const file = write('broken.3mf', 'not a zip');
  const { meta } = extractMetadata(file, 'broken.3mf');
  assert.ok(meta.parseError);
});

test('remoteFileName strips Vietnamese diacritics and odd characters', () => {
  assert.equal(remoteFileName('Bản in thử đẹp.gcode'), 'Ban_in_thu_dep.gcode');
  assert.equal(remoteFileName('../evil/name?.gcode'), 'evil_name_.gcode');
  assert.equal(remoteFileName(''), 'print.gcode');
});
