import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-notify-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const { updateConfig, publicConfig } = await import('../src/core/config.js');
const printers = await import('../src/core/printers.js');
const library = await import('../src/core/library.js');
const jobs = await import('../src/core/jobs.js');
const notify = await import('../src/core/notify.js');

const GCODE = ['; generated by PrusaSlicer 2.8.0', 'M140 S60', ';Z:0.2', ';Z:2', '; estimated printing time (normal mode) = 10m 0s', '; layer_height = 0.2'].join('\n');

const realFetch = globalThis.fetch;
let calls = [];
let reply = { ok: true, result: { chat: { id: 4242 } } };

let printer;
let file;

before(async () => {
  globalThis.fetch = async (url, init) => {
    calls.push({ url: String(url), init });
    return new Response(JSON.stringify(reply), { status: reply.ok ? 200 : 400, headers: { 'content-type': 'application/json' } });
  };
  updateConfig({ notify: { telegram: { enabled: true, botToken: '123:abc', chatId: '4242', includeSnapshot: false } } });
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  printer = printers.addPrinter({ name: 'Sim', driver: 'virtual', connection: { simulationSpeed: 1000 } });
  file = library.addFromContent({ name: 'Chậu cây.gcode', content: GCODE });
  jobs.startQueue();
  notify.startNotifier();
  await waitFor(() => printers.isReady(printer.id));
});

after(async () => {
  notify.stopNotifier();
  jobs.stopQueue();
  jobs.flushJobs();
  await printers.stopAll();
  globalThis.fetch = realFetch;
});

test('Bot token không lọt ra ngoài qua cấu hình công khai', () => {
  assert.equal(publicConfig().notify.telegram.botToken, '***');
  assert.equal(publicConfig().notify.telegram.chatId, '4242');
});

test('In xong thì bắn tin nhắn Telegram kèm tên file, tên máy và thời gian in', async () => {
  calls = [];
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'now' });
  const done = await waitFor(() => (jobs.getJob(job.id).status === 'completed' ? jobs.getJob(job.id) : null));
  const call = await waitFor(() => calls.find((item) => item.url.includes('sendMessage')) ?? null);

  assert.equal(call.url, 'https://api.telegram.org/bot123:abc/sendMessage');
  const body = JSON.parse(call.init.body);
  assert.equal(body.chat_id, '4242');
  assert.equal(body.parse_mode, 'HTML');
  assert.match(body.text, /In xong/);
  assert.match(body.text, /Chậu cây\.gcode/);
  assert.match(body.text, /Sim/);
  assert.match(body.text, /Thời gian in/);
  assert.equal(done.status, 'completed');

  // Một job chỉ báo một lần dù còn sự kiện nào khác trỏ về nó.
  await new Promise((resolve) => setTimeout(resolve, 300));
  assert.equal(calls.filter((item) => item.url.includes('sendMessage')).length, 1);
});

test('Huỷ in không nằm trong danh sách sự kiện thì im lặng', async () => {
  updateConfig({ notify: { telegram: { events: ['completed'] } } });
  calls = [];
  printers.setBedClear(printer.id, true);
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'now' });
  await waitFor(() => jobs.getJob(job.id).status === 'printing');
  await printers.command(printer.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? jobs.getJob(job.id) : null));
  await new Promise((resolve) => setTimeout(resolve, 300));
  assert.equal(calls.length, 0);
  updateConfig({ notify: { telegram: { events: ['completed', 'failed', 'canceled'] } } });
});

test('Thiếu token hoặc chat id thì báo lỗi rõ ràng, Telegram từ chối cũng vậy', async () => {
  updateConfig({ notify: { telegram: { botToken: null, chatId: null } } });
  await assert.rejects(notify.sendTelegram('x'), { key: 'error.telegram_no_token' });
  await assert.rejects(notify.sendTelegram('x', { botToken: 'a:b' }), { key: 'error.telegram_no_chat' });
  updateConfig({ notify: { telegram: { botToken: '123:abc', chatId: '4242' } } });

  reply = { ok: false, description: 'chat not found' };
  await assert.rejects(notify.testTelegram({ chatId: '1' }), (error) => {
    assert.equal(error.key, 'error.telegram_failed');
    assert.match(error.message, /chat not found/);
    return true;
  });
  reply = { ok: true, result: { chat: { id: 4242 } } };
  assert.deepEqual(await notify.testTelegram({}), { sent: true, chatId: 4242 });
});

test('Có ảnh thì gửi qua sendPhoto dạng multipart, ảnh nằm trong trường photo', async () => {
  calls = []
  await notify.sendTelegram('<b>In xong</b>', { photo: { buffer: Buffer.from([0xff, 0xd8, 0xff, 0xd9]), mime: 'image/jpeg' } });
  assert.equal(calls.length, 1);
  assert.match(calls[0].url, /\/sendPhoto$/);
  const form = calls[0].init.body;
  assert.ok(form instanceof FormData);
  assert.equal(form.get('chat_id'), '4242');
  assert.equal(form.get('caption'), '<b>In xong</b>');
  assert.equal(form.get('parse_mode'), 'HTML');
  const photo = form.get('photo');
  assert.equal(photo.type, 'image/jpeg');
  assert.deepEqual(Buffer.from(await photo.arrayBuffer()), Buffer.from([0xff, 0xd8, 0xff, 0xd9]));
});

test('Dấu ngoặc nhọn trong tên file bị thoát để Telegram không hiểu nhầm là thẻ HTML', () => {
  const text = notify.messageFor({
    status: 'failed',
    fileName: '<b>vỏ hộp</b>.gcode',
    printerName: 'Sim & Co',
    error: 'hết nhựa',
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
    startedAt: new Date(Date.now() - 3600_000).toISOString(),
    finishedAt: new Date().toISOString(),
  });
  assert.match(text, /&lt;b&gt;vỏ hộp&lt;\/b&gt;\.gcode/);
  assert.match(text, /Sim &amp; Co/);
  assert.match(text, /1 giờ 0 phút/);
  assert.match(text, /hết nhựa/);
});
