import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-watch-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const { updateConfig } = await import('../src/core/config.js');
const library = await import('../src/core/library.js');
const printers = await import('../src/core/printers.js');
const jobs = await import('../src/core/jobs.js');
const advisor = await import('../src/core/advisor.js');
const watch = await import('../src/core/watch.js');

const GCODE = [
  '; generated by PrusaSlicer 2.8.0',
  '; layer_height = 0.32',
  '; nozzle_diameter = 0.4',
  '; filament_type = PLA',
  '; filament used [g] = 40',
  '; estimated printing time (normal mode) = 10m 0s',
  'M140 S60',
  'M104 S210',
  ';Z:0.2',
  ';Z:3.2',
].join('\n');

/** Đóng vai API nhà cung cấp; `reply` quyết định nội dung trả về cho từng lần gọi. */
let reply = () => ({ status: 200, body: { content: [] } });
const calls = [];
let provider;
let printer;
let file;

before(async () => {
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  provider = await new Promise((resolve) => {
    const server = createServer((req, res) => {
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      });
      req.on('end', () => {
        const parsed = JSON.parse(body);
        calls.push(parsed);
        const result = reply(parsed);
        res.writeHead(result.status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(result.body));
      });
    });
    server.listen(0, '127.0.0.1', () => resolve({ server, url: `http://127.0.0.1:${server.address().port}` }));
  });
  updateConfig({
    ai: { authType: 'api_key', apiKey: 'sk-test', baseUrl: provider.url, model: 'claude-sonnet-5' },
    notify: { telegram: { enabled: false } },
    watch: { enabled: true, intervalMin: 1, firstLayer: true, minConfidence: 0.7, onDetect: 'pause', autoDiagnose: false },
  });
  printer = printers.addPrinter({ name: 'Sim soi anh', driver: 'virtual', connection: { simulationSpeed: 60 } });
  file = library.addFromContent({ name: 'watch-demo.gcode', content: GCODE });
  jobs.startQueue();
  await waitFor(() => printers.isReady(printer.id));
});

after(async () => {
  jobs.stopQueue();
  jobs.flushJobs();
  watch.stopWatcher();
  await printers.stopAll();
  await new Promise((resolve) => provider.server.close(resolve));
});

function verdict(input) {
  return { status: 200, body: { model: 'claude-sonnet-5', content: [{ type: 'tool_use', name: 'report_print_health', input }] } };
}

async function printUntilLayer(layer) {
  printers.setBedClear(printer.id, true);
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'now', confirmBedClear: true });
  await waitFor(() => (printers.statusOf(printer.id).job?.layer >= layer ? true : null));
  return job;
}

test('Soi ảnh: gửi kèm ảnh base64, kết luận lạ bị quy về unclear và mức tin cậy bị kẹp lại', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'chua-biet', issue: 'khong-ro', confidence: 7, summary: 'Nhìn không rõ' });

  const result = await advisor.inspectPrint({ printerId: printer.id });
  const content = calls.at(-1).messages[0].content;
  assert.equal(content[0].type, 'image');
  assert.equal(content[0].source.type, 'base64');
  assert.ok(content[0].source.data.length > 100, 'phải gửi ảnh thật chứ không phải chuỗi rỗng');
  assert.ok(content[1].text.includes('Sim soi anh'));
  assert.equal(result.verdict, 'unclear');
  assert.equal(result.issue, 'other');
  assert.equal(result.confidence, 1);
});

test('Giám sát: máy còn đang gia nhiệt thì chưa soi', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.95, summary: 'Nhựa rối' });

  // Tua chậm để máy nằm lâu ở bước gia nhiệt, đủ thời gian chạy một vòng soi.
  const slow = printers.addPrinter({ name: 'Sim cho nong', driver: 'virtual', connection: { simulationSpeed: 1 } });
  await waitFor(() => printers.isReady(slow.id));
  printers.setBedClear(slow.id, true);
  const job = await jobs.createJob({ printerId: slow.id, fileId: file.id, mode: 'now', confirmBedClear: true });
  await waitFor(() => (printers.statusOf(slow.id).job?.stage === 'heating' ? true : null));

  await watch.runWatchOnce();
  assert.equal(calls.length, 0, 'đang chờ gia nhiệt thì không được gọi AI');
  assert.equal(watch.lastInspection(slow.id), null);

  await printers.command(slow.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
  await printers.removePrinter(slow.id);
});

test('Giám sát: hỏng rõ và đủ tin cậy thì tạm dừng máy, và chỉ báo một lần cho mỗi bản in', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.95, summary: 'Nhựa rối quanh đầu phun', advice: ['Huỷ bản in'] });

  const job = await printUntilLayer(2);
  await watch.runWatchOnce();

  assert.equal(watch.lastInspection(printer.id).issue, 'spaghetti');
  assert.equal(printers.statusOf(printer.id).state, 'paused', 'phải tự tạm dừng khi chắc là hỏng');
  const after = calls.length;

  // Vòng sau vẫn tới hạn nhưng bản in đã bị dừng, không được gọi AI thêm lần nữa.
  await watch.runWatchOnce();
  assert.equal(calls.length, after, 'đã dừng rồi thì thôi soi tiếp');

  await printers.command(printer.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
});

test('Giám sát: chỉ đáng ngờ hoặc tin cậy thấp thì không đụng vào máy', async () => {
  reply = () => verdict({ verdict: 'suspect', issue: 'warping', confidence: 0.9, summary: 'Mép hơi vênh' });
  const job = await printUntilLayer(2);
  await watch.runWatchOnce();
  assert.equal(printers.statusOf(printer.id).state, 'printing', 'nghi ngờ thôi thì không được dừng bản in');

  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.4, summary: 'Có thể hỏng' });
  watch.stopWatcher();
  await watch.runWatchOnce();
  assert.equal(printers.statusOf(printer.id).state, 'printing', 'chưa đủ tin cậy thì cũng không được dừng');

  await printers.command(printer.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
});

test('Phân tích file: cảnh báo tự tính vẫn có kể cả khi mô hình không nêu gì', async () => {
  reply = () => ({
    status: 200,
    body: {
      model: 'claude-sonnet-5',
      content: [{ type: 'tool_use', name: 'review_print_job', input: { verdict: 'ok', summary: 'Nhìn chung in được', findings: [] } }],
    },
  });

  const result = await advisor.analyzePrint({ fileId: file.id, printerId: printer.id });
  const titles = result.findings.map((item) => item.title);
  assert.ok(
    titles.some((title) => title.includes('0.32')),
    `phải tự phát hiện lớp dày quá so với vòi phun, đang có: ${titles.join(' | ')}`,
  );
  assert.equal(result.findings.every((item) => item.source === 'rule'), true);
  assert.equal(result.verdict, 'ok');
});

test('Tự chẩn đoán: mỗi đợt lỗi chỉ hỏi AI một lần', async () => {
  updateConfig({ watch: { autoDiagnose: true } });
  reply = () => ({
    status: 200,
    body: {
      model: 'claude-sonnet-5',
      content: [
        {
          type: 'tool_use',
          name: 'diagnose_printer',
          input: { summary: 'Máy bị dừng khẩn cấp', causes: ['Người dùng bấm M112'], steps: ['Khởi động lại máy'], severity: 'warning' },
        },
      ],
    },
  });

  calls.length = 0;
  watch.startWatcher();
  await printers.command(printer.id, 'gcode', { gcode: 'M112' });
  await waitFor(() => (watch.lastDiagnosis(printer.id)?.summary ? true : null));
  assert.equal(watch.lastDiagnosis(printer.id).summary, 'Máy bị dừng khẩn cấp');

  const after = calls.length;
  await new Promise((resolve) => setTimeout(resolve, 1200));
  assert.equal(calls.length, after, 'máy vẫn lỗi như cũ thì không hỏi lại');

  await printers.command(printer.id, 'gcode', { gcode: 'M999' });
  watch.stopWatcher();
});
