import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { waitFor } from './helpers.js';

process.env.PRINTAGENT3D_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'p3d-watch-'));
process.env.PRINTAGENT3D_LOG_LEVEL = 'error';

const { updateConfig } = await import('../src/core/config.js');
const library = await import('../src/core/library.js');
const printers = await import('../src/core/printers.js');
const jobs = await import('../src/core/jobs.js');
const advisor = await import('../src/core/advisor.js');
const watch = await import('../src/core/watch.js');

const GCODE = [
  '; generated by PrusaSlicer 2.8.0',
  '; layer_height = 0.32',
  '; nozzle_diameter = 0.4',
  '; filament_type = PLA',
  '; filament used [g] = 40',
  '; estimated printing time (normal mode) = 10m 0s',
  'M140 S60',
  'M104 S210',
  ';Z:0.2',
  ';Z:3.2',
].join('\n');

/** Stands in for the provider API; `reply` decides what each call returns. */
let reply = () => ({ status: 200, body: { content: [] } });
const calls = [];
let provider;
let printer;
let file;

before(async () => {
  printers.loadPrinters();
  library.loadLibrary();
  jobs.loadJobs();
  provider = await new Promise((resolve) => {
    const server = createServer((req, res) => {
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      });
      req.on('end', () => {
        const parsed = JSON.parse(body);
        calls.push(parsed);
        const result = reply(parsed);
        res.writeHead(result.status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(result.body));
      });
    });
    server.listen(0, '127.0.0.1', () => resolve({ server, url: `http://127.0.0.1:${server.address().port}` }));
  });
  updateConfig({
    ai: { authType: 'api_key', apiKey: 'sk-test', baseUrl: provider.url, model: 'claude-sonnet-5' },
    notify: { telegram: { enabled: false } },
    watch: { enabled: true, intervalMin: 1, firstLayer: true, minConfidence: 0.7, onDetect: 'pause', autoDiagnose: false },
  });
  printer = printers.addPrinter({ name: 'Sim soi anh', driver: 'virtual', connection: { simulationSpeed: 60 } });
  file = library.addFromContent({ name: 'watch-demo.gcode', content: GCODE });
  jobs.startQueue();
  await waitFor(() => printers.isReady(printer.id));
});

after(async () => {
  jobs.stopQueue();
  jobs.flushJobs();
  watch.stopWatcher();
  await printers.stopAll();
  await new Promise((resolve) => provider.server.close(resolve));
});

function verdict(input) {
  return { status: 200, body: { model: 'claude-sonnet-5', content: [{ type: 'tool_use', name: 'report_print_health', input }] } };
}

async function printUntilLayer(layer) {
  printers.setBedClear(printer.id, true);
  const job = await jobs.createJob({ printerId: printer.id, fileId: file.id, mode: 'now', confirmBedClear: true });
  await waitFor(() => (printers.statusOf(printer.id).job?.layer >= layer ? true : null));
  return job;
}

test('Inspection: sends a base64 image, an unknown verdict falls back to unclear and confidence is clamped', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'chua-biet', issue: 'khong-ro', confidence: 7, summary: 'Cannot tell' });

  const result = await advisor.inspectPrint({ printerId: printer.id });
  const content = calls.at(-1).messages[0].content;
  assert.equal(content[0].type, 'image');
  assert.equal(content[0].source.type, 'base64');
  assert.ok(content[0].source.data.length > 100, 'must send a real image, not an empty string');
  assert.ok(content[1].text.includes('Sim soi anh'));
  assert.equal(result.verdict, 'unclear');
  assert.equal(result.issue, 'other');
  assert.equal(result.confidence, 1);
});

test('Watch: no inspection while the printer is still heating', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.95, summary: 'Tangled filament' });

  // A slow simulation keeps the printer in the heating stage long enough for one watch pass.
  const slow = printers.addPrinter({ name: 'Sim cho nong', driver: 'virtual', connection: { simulationSpeed: 1 } });
  await waitFor(() => printers.isReady(slow.id));
  printers.setBedClear(slow.id, true);
  const job = await jobs.createJob({ printerId: slow.id, fileId: file.id, mode: 'now', confirmBedClear: true });
  await waitFor(() => (printers.statusOf(slow.id).job?.stage === 'heating' ? true : null));

  await watch.runWatchOnce();
  assert.equal(calls.length, 0, 'no AI call while still waiting on heating');
  assert.equal(watch.lastInspection(slow.id), null);

  await printers.command(slow.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
  await printers.removePrinter(slow.id);
});

test('Watch: a clear failure with enough confidence pauses the printer, reported once per print', async () => {
  calls.length = 0;
  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.95, summary: 'Filament tangled around the nozzle', advice: ['Cancel the print'] });

  const job = await printUntilLayer(2);
  await watch.runWatchOnce();

  assert.equal(watch.lastInspection(printer.id).issue, 'spaghetti');
  assert.equal(printers.statusOf(printer.id).state, 'paused', 'must pause itself once the failure is certain');
  const after = calls.length;

  // The next pass is due, but the print is already paused, so there must be no further AI call.
  await watch.runWatchOnce();
  assert.equal(calls.length, after, 'already paused, so stop inspecting');

  await printers.command(printer.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
});

test('Watch: a mere suspicion or low confidence leaves the printer alone', async () => {
  reply = () => verdict({ verdict: 'suspect', issue: 'warping', confidence: 0.9, summary: 'Edge slightly warped' });
  const job = await printUntilLayer(2);
  await watch.runWatchOnce();
  assert.equal(printers.statusOf(printer.id).state, 'printing', 'suspicion alone must not stop the print');

  reply = () => verdict({ verdict: 'failed', issue: 'spaghetti', confidence: 0.4, summary: 'Possibly failed' });
  watch.stopWatcher();
  await watch.runWatchOnce();
  assert.equal(printers.statusOf(printer.id).state, 'printing', 'too little confidence must not stop it either');

  await printers.command(printer.id, 'cancel');
  await waitFor(() => (jobs.getJob(job.id).status === 'canceled' ? true : null));
});

test('File analysis: rule-based findings still appear even when the model reports none', async () => {
  reply = () => ({
    status: 200,
    body: {
      model: 'claude-sonnet-5',
      content: [{ type: 'tool_use', name: 'review_print_job', input: { verdict: 'ok', summary: 'Looks printable overall', findings: [] } }],
    },
  });

  const result = await advisor.analyzePrint({ fileId: file.id, printerId: printer.id });
  const titles = result.findings.map((item) => item.title);
  assert.ok(
    titles.some((title) => title.includes('0.32')),
    `must detect a layer too thick for the nozzle, got: ${titles.join(' | ')}`,
  );
  assert.equal(result.findings.every((item) => item.source === 'rule'), true);
  assert.equal(result.verdict, 'ok');
});

test('Auto-diagnose: one AI call per error episode', async () => {
  updateConfig({ watch: { autoDiagnose: true } });
  reply = () => ({
    status: 200,
    body: {
      model: 'claude-sonnet-5',
      content: [
        {
          type: 'tool_use',
          name: 'diagnose_printer',
          input: { summary: 'Printer emergency stopped', causes: ['User sent M112'], steps: ['Restart the printer'], severity: 'warning' },
        },
      ],
    },
  });

  calls.length = 0;
  watch.startWatcher();
  await printers.command(printer.id, 'gcode', { gcode: 'M112' });
  await waitFor(() => (watch.lastDiagnosis(printer.id)?.summary ? true : null));
  assert.equal(watch.lastDiagnosis(printer.id).summary, 'Printer emergency stopped');

  const after = calls.length;
  await new Promise((resolve) => setTimeout(resolve, 1200));
  assert.equal(calls.length, after, 'the same error still standing means no second ask');

  await printers.command(printer.id, 'gcode', { gcode: 'M999' });
  watch.stopWatcher();
});
