import { openSync, closeSync, fstatSync } from 'node:fs';
import path from 'node:path';
import { inflateSync, inflateRawSync } from 'node:zlib';
import { attr, each3mfTriangle, eachModelTriangle, readRange } from './mesh.js';
import { openZip } from './zip.js';

export const PRINTABLE_EXTENSIONS = ['.gcode', '.gco', '.g', '.bgcode', '.3mf'];
export const MODEL_EXTENSIONS = ['.stl', '.obj'];
export const SUPPORTED_EXTENSIONS = [...PRINTABLE_EXTENSIONS, ...MODEL_EXTENSIONS];

const HEAD_BYTES = 1024 * 1024;
const TAIL_BYTES = 512 * 1024;

export function fileFormat(name) {
  const lower = String(name).toLowerCase();
  if (lower.endsWith('.3mf')) return '3mf';
  if (lower.endsWith('.bgcode')) return 'bgcode';
  if (['.gcode', '.gco', '.g'].includes(path.extname(lower))) return 'gcode';
  if (MODEL_EXTENSIONS.includes(path.extname(lower))) return 'model';
  return null;
}

/** "1d 2h 3m 4s", "2h 30m", "45m 10s" -> seconds. */
export function parseDuration(value) {
  if (value === undefined || value === null) return null;
  const text = String(value).trim().toLowerCase();
  if (/^\d+(\.\d+)?$/.test(text)) return Math.round(Number(text));
  let total = 0;
  let matched = false;
  for (const [pattern, factor] of [
    [/(\d+(?:\.\d+)?)\s*d/, 86400],
    [/(\d+(?:\.\d+)?)\s*h/, 3600],
    [/(\d+(?:\.\d+)?)\s*m(?!s)/, 60],
    [/(\d+(?:\.\d+)?)\s*s/, 1],
  ]) {
    const match = text.match(pattern);
    if (match) {
      total += Number(match[1]) * factor;
      matched = true;
    }
  }
  const words = text.match(/(\d+)\s*hours?\s*(\d+)?\s*(?:minutes?)?/);
  if (!matched && words) return Number(words[1]) * 3600 + Number(words[2] ?? 0) * 60;
  return matched ? Math.round(total) : null;
}

function sumNumbers(value) {
  if (value === undefined || value === null) return null;
  const numbers = String(value)
    .split(/[,;]/)
    .map((part) => Number.parseFloat(part))
    .filter((part) => Number.isFinite(part));
  if (numbers.length === 0) return null;
  return Math.round(numbers.reduce((sum, item) => sum + item, 0) * 100) / 100;
}

function firstNumber(value) {
  if (value === undefined || value === null) return null;
  const number = Number.parseFloat(String(value).split(/[,;]/)[0]);
  return Number.isFinite(number) ? number : null;
}

function collectPairs(text, pairs) {
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    const body = line.startsWith(';') ? line.slice(1) : line.includes('=') && !/^[GMT]\d/i.test(line) ? line : null;
    if (body === null) continue;
    for (const segment of body.split(';')) {
      const match = segment.match(/^\s*([^=:]{1,80}?)\s*[=:]\s*(.+?)\s*$/);
      if (!match) continue;
      const key = match[1].toLowerCase();
      if (!(key in pairs)) pairs[key] = match[2];
    }
  }
}

function detectSlicer(text) {
  const patterns = [
    /generated by (PrusaSlicer[^\s]*\s[\d.]+[^\s]*)/i,
    /generated by (SuperSlicer[^\s]*\s[\d.]+[^\s]*)/i,
    /generated by (OrcaSlicer[^\s]*\s[\d.]+[^\s]*)/i,
    /(BambuStudio\s[\d.]+)/i,
    /Generated with (Cura_SteamEngine\s[\d.]+)/i,
    /(Simplify3D\(R\) Version [\d.]+)/i,
    /Sliced by (ideaMaker\s?[\d.]*)/i,
    /generated by (Slic3r[^\s]*\s[\d.]+)/i,
    /generated by ([A-Za-z]+Slicer[^\s]*\s[\d.]+)/i,
  ];
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match) return match[1].replace('Cura_SteamEngine', 'Cura').trim();
  }
  return null;
}

function extractThumbnail(text) {
  const pattern = /;\s*thumbnail(?:_(PNG|JPG|QOI))?\s+begin\s+(\d+)x(\d+)\s+\d+\s*\r?\n([\s\S]*?);\s*thumbnail(?:_\w+)?\s+end/gi;
  let best = null;
  for (const match of text.matchAll(pattern)) {
    const format = (match[1] ?? 'PNG').toUpperCase();
    if (format === 'QOI') continue;
    const width = Number(match[2]);
    const height = Number(match[3]);
    if (best && width * height <= best.width * best.height) continue;
    const data = match[4].replace(/^\s*;\s?/gm, '').replace(/\s/g, '');
    best = { width, height, mime: format === 'JPG' ? 'image/jpeg' : 'image/png', data };
  }
  if (!best) return null;
  const buffer = Buffer.from(best.data, 'base64');
  return buffer.length ? { buffer, mime: best.mime, width: best.width, height: best.height } : null;
}

function interpretPairs(pairs, text) {
  const pick = (...keys) => keys.map((key) => pairs[key]).find((value) => value !== undefined && value !== '');
  let estimatedTime =
    parseDuration(pick('total estimated time')) ??
    parseDuration(pick('estimated printing time (normal mode)', 'estimated printing time')) ??
    parseDuration(pick('time', 'print.time', 'print time', 'build time')) ??
    parseDuration(pick('model printing time'));
  if (estimatedTime === 0) estimatedTime = null;

  let filamentLengthMm = sumNumbers(pick('filament used [mm]', 'total filament length [mm]', 'filament length'));
  const curaMeters = pick('filament used');
  if (filamentLengthMm === null && curaMeters) {
    const meters = sumNumbers(curaMeters.replace(/m\b/g, ''));
    if (meters !== null) filamentLengthMm = Math.round(meters * 1000);
  }
  const materialUsed = pick('material#1 used');
  if (filamentLengthMm === null && materialUsed) filamentLengthMm = firstNumber(materialUsed);

  const layerCount = firstNumber(pick('total layers count', 'total layer number', 'layer_count', 'layer count'));
  let nozzleTemp = firstNumber(pick('first_layer_temperature', 'temperature', 'nozzle_temperature_initial_layer', 'extruder_train.0.initial_temperature'));
  let bedTemp = firstNumber(pick('first_layer_bed_temperature', 'bed_temperature', 'hot_plate_temp_initial_layer', 'build_plate.initial_temperature'));
  if (nozzleTemp === null) {
    const match = text.match(/^M10[49]\s+(?:T\d\s+)?S(\d+(?:\.\d+)?)/m);
    if (match) nozzleTemp = Number(match[1]);
  }
  if (bedTemp === null) {
    const match = text.match(/^M1(?:40|90)\s+S(\d+(?:\.\d+)?)/m);
    if (match) bedTemp = Number(match[1]);
  }

  return {
    estimatedTime,
    filamentLengthMm,
    filamentWeightG: sumNumbers(pick('filament used [g]', 'total filament used [g]', 'total filament weight [g]', 'plastic weight')),
    filamentType: pick('filament_type', 'filament type')?.split(/[;,]/)[0]?.trim() ?? null,
    layerHeight: firstNumber(pick('layer_height', 'layer height')),
    nozzleDiameter: firstNumber(pick('nozzle_diameter', 'extruder_train.0.nozzle.diameter')),
    layerCount: layerCount ? Math.round(layerCount) : null,
    printerModel: pick('printer_model', 'target_machine.name', 'printer_settings_id') ?? null,
    nozzleTemp: nozzleTemp ? Math.round(nozzleTemp) : null,
    bedTemp: bedTemp ? Math.round(bedTemp) : null,
    maxZ: firstNumber(pick('max_z_height', 'maxz')),
  };
}

function parseGcode(filePath) {
  const fd = openSync(filePath, 'r');
  try {
    const size = fstatSync(fd).size;
    const head = readRange(fd, 0, Math.min(size, HEAD_BYTES)).toString('utf8');
    const tail = size > HEAD_BYTES ? readRange(fd, Math.max(HEAD_BYTES, size - TAIL_BYTES), TAIL_BYTES).toString('utf8') : '';
    const pairs = {};
    collectPairs(head, pairs);
    collectPairs(tail, pairs);
    const meta = { slicer: detectSlicer(head) ?? detectSlicer(tail), ...interpretPairs(pairs, head) };
    const lastZ = [...(tail || head).matchAll(/^;\s*Z:\s*(\d+(?:\.\d+)?)/gm)].pop();
    if (meta.maxZ === null && lastZ) meta.maxZ = Number(lastZ[1]);
    if (meta.layerCount === null && meta.maxZ && meta.layerHeight) meta.layerCount = Math.round(meta.maxZ / meta.layerHeight);
    return {
      meta,
      thumbnail: extractThumbnail(head) ?? extractThumbnail(tail),
    };
  } finally {
    closeSync(fd);
  }
}

const BGCODE_BLOCK = { GCODE: 1, THUMBNAIL: 5 };

function decompressBlock(data, compression) {
  if (compression === 0) return data;
  if (compression === 1) {
    try {
      return inflateSync(data);
    } catch {
      return inflateRawSync(data);
    }
  }
  return null;
}

/** Prusa binary G-code: metadata and thumbnails sit in the first blocks, stop at the G-code block. */
function parseBgcode(filePath) {
  const fd = openSync(filePath, 'r');
  try {
    const size = fstatSync(fd).size;
    const header = readRange(fd, 0, 10);
    if (header.toString('ascii', 0, 4) !== 'GCDE') throw new Error('Invalid bgcode header');
    const checksumSize = header.readUInt16LE(8) === 1 ? 4 : 0;
    const pairs = {};
    let thumbnail = null;
    let offset = 10;
    for (let guard = 0; guard < 64 && offset + 8 <= size; guard += 1) {
      const blockHead = readRange(fd, offset, 12);
      const type = blockHead.readUInt16LE(0);
      const compression = blockHead.readUInt16LE(2);
      const uncompressedSize = blockHead.readUInt32LE(4);
      const headerSize = compression === 0 ? 8 : 12;
      const dataSize = compression === 0 ? uncompressedSize : blockHead.readUInt32LE(8);
      const paramsSize = type === BGCODE_BLOCK.THUMBNAIL ? 6 : 2;
      if (type === BGCODE_BLOCK.GCODE) break;
      const params = readRange(fd, offset + headerSize, paramsSize);
      const raw = readRange(fd, offset + headerSize + paramsSize, dataSize);
      const data = decompressBlock(raw, compression);
      if (data && type === BGCODE_BLOCK.THUMBNAIL) {
        const format = params.readUInt16LE(0);
        const width = params.readUInt16LE(2);
        const height = params.readUInt16LE(4);
        if (format !== 2 && (!thumbnail || width * height > thumbnail.width * thumbnail.height)) {
          thumbnail = { buffer: data, mime: format === 1 ? 'image/jpeg' : 'image/png', width, height };
        }
      } else if (data) {
        collectPairs(data.toString('utf8'), pairs);
      }
      offset += headerSize + paramsSize + dataSize + checksumSize;
    }
    return { meta: { slicer: pairs.producer ?? null, ...interpretPairs(pairs, '') }, thumbnail };
  } finally {
    closeSync(fd);
  }
}

function parsePlates(xml) {
  const plates = [];
  for (const block of xml.matchAll(/<plate>([\s\S]*?)<\/plate>/g)) {
    const values = {};
    for (const item of block[1].matchAll(/<metadata\s+key="([^"]+)"\s+value="([^"]*)"/g)) values[item[1]] = item[2];
    const filaments = [...block[1].matchAll(/<filament\s+([^>]*?)\/>/g)].map((match) => {
      const attrs = Object.fromEntries([...match[1].matchAll(/(\w+)="([^"]*)"/g)].map((item) => [item[1], item[2]]));
      return { id: Number(attrs.id), type: attrs.type ?? null, color: attrs.color ?? null, usedG: firstNumber(attrs.used_g) };
    });
    plates.push({
      index: Number(values.index) || plates.length + 1,
      estimatedTime: firstNumber(values.prediction),
      weightG: firstNumber(values.weight),
      printerModelId: values.printer_model_id ?? null,
      nozzleDiameter: firstNumber(values.nozzle_diameters),
      filaments,
    });
  }
  return plates;
}

/** An unsliced 3MF holds only the mesh; measure size and overhangs to suggest settings. */
function measure3mf(zip) {
  const mesh = meshAccumulator();
  each3mfTriangle(zip, mesh.add);
  return mesh.result();
}

function parse3mf(filePath) {
  const zip = openZip(filePath);
  try {
    const plateGcodes = zip.entries
      .map((entry) => entry.name.match(/^Metadata\/plate_(\d+)\.gcode$/))
      .filter(Boolean)
      .map((match) => Number(match[1]))
      .sort((a, b) => a - b);
    const sliceInfo = zip.read('Metadata/slice_info.config', { maxBytes: 4 * 1024 * 1024 });
    const plates = sliceInfo ? parsePlates(sliceInfo.toString('utf8')) : [];
    const sliced = plateGcodes.length > 0;
    const knownPlates = sliced
      ? plateGcodes.map((index) => ({
          index,
          estimatedTime: null,
          weightG: null,
          filaments: [],
          ...plates.find((plate) => plate.index === index),
          gcode: `Metadata/plate_${index}.gcode`,
        }))
      : [];

    let slicer = null;
    const model = zip.read('3D/3dmodel.model', { maxBytes: 256 * 1024 });
    if (model) {
      const application = model.toString('utf8').match(/<metadata name="Application">([^<]+)<\/metadata>/);
      slicer = application ? application[1].replace(/-/g, ' ') : null;
    }

    const thumbnailName = [
      knownPlates[0] ? `Metadata/plate_${knownPlates[0].index}.png` : null,
      'Metadata/plate_1.png',
      'Metadata/thumbnail.png',
      'Thumbnails/thumbnail.png',
    ].find((name) => name && zip.has(name));
    const thumbnailBuffer = thumbnailName ? zip.read(thumbnailName, { maxBytes: 8 * 1024 * 1024 }) : null;

    const first = knownPlates[0];
    return {
      meta: {
        slicer,
        sliced,
        ...(sliced ? {} : measure3mf(zip)),
        plates: knownPlates,
        estimatedTime: first?.estimatedTime ?? null,
        filamentWeightG: first?.weightG ?? null,
        filamentType: first?.filaments?.[0]?.type ?? null,
        nozzleDiameter: first?.nozzleDiameter ?? null,
      },
      thumbnail: thumbnailBuffer ? { buffer: thumbnailBuffer, mime: 'image/png' } : null,
    };
  } finally {
    zip.close();
  }
}

const PLATE_JSON = /^Metadata\/plate_(\d+)\.json$/;

/** `printable_area` and `bed_exclude_area` are vertex lists in "XxY" form. */
function parsePolygon(value) {
  return (Array.isArray(value) ? value : [])
    .map((point) => String(point).split('x').map(Number))
    .filter((point) => point.length === 2 && point.every(Number.isFinite));
}

export function parseBed(config) {
  const outline = parsePolygon(config.printable_area);
  if (outline.length < 3) return null;
  const xs = outline.map((point) => point[0]);
  const ys = outline.map((point) => point[1]);
  return {
    minX: Math.min(...xs),
    minY: Math.min(...ys),
    maxX: Math.max(...xs),
    maxY: Math.max(...ys),
    maxZ: firstNumber(config.printable_height),
    model: config.printer_model || null,
    exclude: parsePolygon(config.bed_exclude_area),
  };
}

/**
 * Real position of every object on the plate, read straight from the sliced 3MF so even long-imported files can be viewed.
 * `Metadata/top_N.png` is a top-down orthographic render whose edge spans the bed's long side, centered on the bed.
 */
export function readPlateLayout(filePath, plate) {
  const zip = openZip(filePath);
  try {
    const indexes = zip.entries
      .map((entry) => entry.name.match(PLATE_JSON))
      .filter(Boolean)
      .map((match) => Number(match[1]))
      .sort((left, right) => left - right);
    if (indexes.length === 0) return null;
    const index = indexes.includes(Number(plate)) ? Number(plate) : indexes[0];
    const data = JSON.parse(zip.read(`Metadata/plate_${index}.json`, { maxBytes: 4 * 1024 * 1024 }).toString('utf8'));
    const settings = zip.read('Metadata/project_settings.config', { maxBytes: 16 * 1024 * 1024 });
    return {
      plate: index,
      plates: indexes,
      bed: settings ? parseBed(JSON.parse(settings.toString('utf8'))) : null,
      bounds: Array.isArray(data.bbox_all) ? data.bbox_all : null,
      objects: (data.bbox_objects ?? [])
        .filter((item) => Array.isArray(item.bbox) && item.bbox.length === 4)
        .map((item) => ({ name: item.name || null, bbox: item.bbox, area: firstNumber(item.area) })),
      hasImage: zip.has(`Metadata/top_${index}.png`),
    };
  } finally {
    zip.close();
  }
}

export function readPlateImage(filePath, plate) {
  const zip = openZip(filePath);
  try {
    const name = `Metadata/top_${Number(plate) || 1}.png`;
    return zip.has(name) ? zip.read(name, { maxBytes: 16 * 1024 * 1024 }) : null;
  } finally {
    zip.close();
  }
}

const MAX_MESH_TRIANGLES = 1200000;
/** Adjacent triangles write a shared vertex with the same value, welding at 0.1 micron is enough to cut the vertex count sent out. */
const MESH_WELD = 1e4;

function tagBody(chunk, close) {
  const end = chunk.indexOf(close);
  return end === -1 ? chunk : chunk.slice(0, end);
}

/** Display name and plate of every object, written by BambuStudio in `Metadata/model_settings.config`. */
function readModelSettings(zip) {
  const entry = 'Metadata/model_settings.config';
  const names = new Map();
  const plateOf = new Map();
  if (!zip.has(entry)) return { names, plateOf };
  const text = zip.read(entry, { maxBytes: 8 * 1024 * 1024 }).toString('utf8');
  for (const chunk of text.split('<object ').slice(1)) {
    const body = tagBody(chunk, '</object>');
    const id = attr(body.slice(0, body.indexOf('>') + 1), 'id');
    const name = body.match(/<metadata key="name" value="([^"]*)"/);
    if (id && name) names.set(id, name[1]);
  }
  for (const chunk of text.split('<plate>').slice(1)) {
    const body = tagBody(chunk, '</plate>');
    const index = Number(body.match(/key="plater_id" value="(\d+)"/)?.[1]);
    if (!Number.isFinite(index)) continue;
    for (const match of body.matchAll(/key="object_id" value="(\d+)"/g)) plateOf.set(match[1], index);
  }
  return { names, plateOf };
}

/** Group triangles per object, welding duplicate vertices to cut the data sent to the browser several times over. */
function meshParts(limit) {
  const parts = new Map();
  let triangles = 0;
  let dropped = 0;

  const add = (a, b, c, item) => {
    if (triangles >= limit) {
      dropped += 1;
      return;
    }
    triangles += 1;
    const key = item?.index ?? 0;
    let part = parts.get(key);
    if (!part) {
      part = { objectId: item?.objectId ?? null, name: item?.name ?? null, lookup: new Map(), coords: [], indices: [], min: [Infinity, Infinity, Infinity], max: [-Infinity, -Infinity, -Infinity] };
      parts.set(key, part);
    }
    for (const point of [a, b, c]) {
      const hash = `${Math.round(point[0] * MESH_WELD)},${Math.round(point[1] * MESH_WELD)},${Math.round(point[2] * MESH_WELD)}`;
      let index = part.lookup.get(hash);
      if (index === undefined) {
        index = part.coords.length / 3;
        part.lookup.set(hash, index);
        part.coords.push(point[0], point[1], point[2]);
        for (let axis = 0; axis < 3; axis += 1) {
          if (point[axis] < part.min[axis]) part.min[axis] = point[axis];
          if (point[axis] > part.max[axis]) part.max[axis] = point[axis];
        }
      }
      part.indices.push(index);
    }
  };

  const result = (keep) => ({
    dropped,
    objects: [...parts.entries()]
      .filter(([, part]) => part.indices.length > 0 && (keep ? keep(part) : true))
      .sort((left, right) => left[0] - right[0])
      .map(([item, part]) => ({
        item,
        name: part.name,
        objectId: part.objectId,
        triangles: part.indices.length / 3,
        bbox: [...part.min, ...part.max],
        vertices: Float32Array.from(part.coords),
        indices: Uint32Array.from(part.indices),
      })),
  });

  return { add, result };
}

/**
 * The real model mesh in bed coordinates, for the 3D viewer.
 * Slicer 3MF keeps meshes in `3D/Objects/*.model` and pushes the bed position into the build item transform.
 */
export function readPlateMesh(filePath, name, plate) {
  const format = fileFormat(name);
  if (format === 'model') {
    const mesh = meshParts(MAX_MESH_TRIANGLES);
    eachModelTriangle(filePath, name, (a, b, c) => mesh.add(a, b, c, { index: 0, name: path.basename(String(name)) }));
    const { objects, dropped } = mesh.result();
    return objects.length > 0 ? { plate: 1, plates: [], bed: null, dropped, objects } : null;
  }
  if (format !== '3mf') return null;

  const zip = openZip(filePath);
  try {
    const indexes = zip.entries
      .map((entry) => entry.name.match(PLATE_JSON))
      .filter(Boolean)
      .map((match) => Number(match[1]))
      .sort((left, right) => left - right);
    const index = indexes.includes(Number(plate)) ? Number(plate) : (indexes[0] ?? 1);
    const { names, plateOf } = readModelSettings(zip);
    const mesh = meshParts(MAX_MESH_TRIANGLES);
    each3mfTriangle(zip, mesh.add);
    // Only filter by plate when the file actually records which object belongs to which plate, so unusual files do not end up hiding the model.
    const filtered = plateOf.size > 0 && indexes.length > 1;
    const { objects, dropped } = mesh.result((part) => !filtered || plateOf.get(String(part.objectId)) === index);
    if (objects.length === 0) return null;
    const settings = zip.has('Metadata/project_settings.config') ? zip.read('Metadata/project_settings.config', { maxBytes: 16 * 1024 * 1024 }) : null;
    return {
      plate: index,
      plates: indexes,
      bed: settings ? parseBed(JSON.parse(settings.toString('utf8'))) : null,
      dropped,
      objects: objects.map((object) => ({ ...object, name: names.get(String(object.objectId)) ?? object.name })),
    };
  } finally {
    zip.close();
  }
}

/**
 * Pack the mesh into a binary stream: 4 bytes of JSON descriptor length, the descriptor (padded to 4 bytes),
 * then each object's Float32 coordinates and Uint32 indices back to back.
 */
export function packMesh(mesh) {
  const header = Buffer.from(
    JSON.stringify({
      plate: mesh.plate,
      plates: mesh.plates,
      bed: mesh.bed,
      dropped: mesh.dropped,
      objects: mesh.objects.map((object) => ({
        item: object.item,
        name: object.name,
        triangles: object.triangles,
        bbox: object.bbox.map((value) => Math.round(value * 1000) / 1000),
        vertexCount: object.vertices.length / 3,
        indexCount: object.indices.length,
      })),
    }),
    'utf8',
  );
  const padded = Math.ceil(header.length / 4) * 4;
  const body = mesh.objects.reduce((sum, object) => sum + object.vertices.byteLength + object.indices.byteLength, 0);
  const buffer = Buffer.alloc(4 + padded + body);
  buffer.writeUInt32LE(header.length, 0);
  header.copy(buffer, 4);
  let at = 4 + padded;
  for (const object of mesh.objects) {
    Buffer.from(object.vertices.buffer, object.vertices.byteOffset, object.vertices.byteLength).copy(buffer, at);
    at += object.vertices.byteLength;
    Buffer.from(object.indices.buffer, object.indices.byteOffset, object.indices.byteLength).copy(buffer, at);
    at += object.indices.byteLength;
  }
  return buffer;
}

/** Faces tilted more than 30 degrees from horizontal and pointing down need support. */
const OVERHANG_COS = Math.cos((30 * Math.PI) / 180);
const MAX_SAMPLE_TRIANGLES = 1500000;

function meshAccumulator() {
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  let triangles = 0;
  let area = 0;
  let volume = 0;
  // Downward faces are bucketed by height; those sitting on the bed need no support and are dropped once the bottom is known.
  const overhangByLevel = new Map();

  const add = (a, b, c) => {
    triangles += 1;
    for (const point of [a, b, c]) {
      for (let axis = 0; axis < 3; axis += 1) {
        if (point[axis] < min[axis]) min[axis] = point[axis];
        if (point[axis] > max[axis]) max[axis] = point[axis];
      }
    }
    const ux = b[0] - a[0];
    const uy = b[1] - a[1];
    const uz = b[2] - a[2];
    const vx = c[0] - a[0];
    const vy = c[1] - a[1];
    const vz = c[2] - a[2];
    const nx = uy * vz - uz * vy;
    const ny = uz * vx - ux * vz;
    const nz = ux * vy - uy * vx;
    const length = Math.hypot(nx, ny, nz);
    if (length === 0) return;
    const faceArea = length / 2;
    area += faceArea;
    if (nz / length < -OVERHANG_COS) {
      const level = Math.round(Math.max(a[2], b[2], c[2]) * 10);
      overhangByLevel.set(level, (overhangByLevel.get(level) ?? 0) + faceArea);
    }
    volume += (a[0] * (b[1] * c[2] - b[2] * c[1]) + a[1] * (b[2] * c[0] - b[0] * c[2]) + a[2] * (b[0] * c[1] - b[1] * c[0])) / 6;
  };

  const result = (total = triangles) => {
    if (triangles === 0) return {};
    const round = (value, digits) => Math.round(value * 10 ** digits) / 10 ** digits;
    const scale = total / triangles;
    const floor = Math.round((min[2] + 0.1) * 10);
    let overhangArea = 0;
    for (const [level, value] of overhangByLevel) if (level > floor) overhangArea += value;
    return {
      triangles: total,
      size: { x: round(max[0] - min[0], 1), y: round(max[1] - min[1], 1), z: round(max[2] - min[2], 1) },
      volumeCm3: round((Math.abs(volume) * scale) / 1000, 2),
      overhangRatio: area > 0 ? round(overhangArea / area, 3) : 0,
    };
  };

  return { add, result };
}

function parseModel(filePath, name) {
  const mesh = meshAccumulator();
  const total = eachModelTriangle(filePath, name, mesh.add, { maxSample: MAX_SAMPLE_TRIANGLES });
  return mesh.result(total);
}

/** Read print info (estimated time, filament, temperatures, preview image) from a slicer-exported file. */
export function extractMetadata(filePath, name = filePath) {
  const format = fileFormat(name);
  const empty = { meta: { format }, thumbnail: null };
  try {
    if (format === 'gcode') {
      const result = parseGcode(filePath);
      return { meta: { format, ...result.meta }, thumbnail: result.thumbnail };
    }
    if (format === 'bgcode') {
      const result = parseBgcode(filePath);
      return { meta: { format, ...result.meta }, thumbnail: result.thumbnail };
    }
    if (format === '3mf') {
      const result = parse3mf(filePath);
      return { meta: { format, ...result.meta }, thumbnail: result.thumbnail };
    }
    if (format === 'model') return { meta: { format, ...parseModel(filePath, name) }, thumbnail: null };
  } catch (error) {
    return { meta: { ...empty.meta, parseError: error.message }, thumbnail: null };
  }
  return empty;
}
